### ISSUE TITLE
no data 

### ISSUE THREAD

**Issue by bwang398** [Staroon/zabbix-hadoop-template#2]
你好，zabbix中没有数据是怎么回事？

在过去的2分钟内未获取到主机[hd-nn-02]上NameNode的任何数据，请检查数据采集器的日志或者查看该主机NameNode运行状态

**Comment by Staroon** [comment]
不好意思今天才看到这个问题，不知道您的问题解决没？
没有的话，
请检查数据采集器的日志，没有日志我也无法判断是什么原因
