### ISSUE TITLE
没有数据

### ISSUE THREAD

**Issue by bobo200128docker** [Staroon/zabbix-hadoop-template#3]
我的是zabbix3.4
ubuntu14.04
hdfs是2.7.2

**Comment by bobo200128docker** [comment]
NameNode数据采集器

**Comment by bobo200128docker** [comment]
sh: 1: /usr/lib/zabbix/externalscripts/cluster-hadoop-plugin.sh: not found

**Comment by bobo200128docker** [comment]
这个文件其实是有的，为什么还报错

**Comment by Staroon** [comment]
文件可执行权限给了吗? chmod +x ..

**Comment by bobo200128docker** [comment]
默认就有的，755，
