### ISSUE TITLE
trigger 当前处于Active状态的NameNode主机为: {HOSTNAME} issue

### ISSUE THREAD

**Issue by wavelet123** [Staroon/zabbix-hadoop-template#6]
hi,
我看日志，已经取到值了，但是还有会有 当前处于Active状态的NameNode主机为: {HOSTNAME} 
这个触发器告警，能不能帮忙看下是什么原因？

hb1117 hadoop_version 2.6.4
hb1117 heap_memory 578.5
hb1117 heap_memory_used 280.99536
hb1117 start_time 2018-08-06 13:34:51
hb1117 non_heap_memory_used 82.29946
hb1117 namenode_state active
hb1117 all_memory_used 363.29482
hb1117 commited_non_heap_memory 84.765625
hb1117 max_heap_memory 889.0

谢谢

**Comment by Staroon** [comment]
这个是我故意添加上去的，用于提示高可用集群处于active状态的NameNode是哪个主机，你不想看到的话可以删掉这个触发器

**Comment by wavelet123** [comment]
理解了，谢谢
